name: Débito Técnico
description: Relate um débito técnico.
title: "[Débito Técnico]: "
labels: ["fdsk-teste-label", "fdsk-debito"]

body:
  - type: markdown
    attributes:
      value: |
        ## Relatório de Débito Técnico

        Obrigado por relatar um débito técnico! Este modelo ajudará a coletar informações detalhadas sobre o problema. Preencher todas as seções relevantes nos permitirá entender completamente o que precisa ser melhorado e priorizar a resolução.

        **Nota:** Certifique-se de incluir o máximo de detalhes possível. Quanto mais informações fornecidas, mais fácil será identificar e resolver o problema.

  - type: markdown
    attributes:
      value: |
        **---**

  - type: dropdown
    id: tipo_debito_tecnico
    attributes:
      label: Tipo de Débito Técnico
      description: Selecione o tipo de débito técnico associado ao problema.
      options:
        - Código Duplicado
        - Falta de Testes Automatizados
        - Arquitetura Pobre
        - Dependências Desatualizadas
        - Documentação Incompleta
        - Performance Degradada
        - Complexidade Ciclomática Alta
        - Outros
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **---**

  - type: textarea
    id: descricao_problema
    attributes:
      label: Descrição do Débito Técnico
      description: Descreva detalhadamente o débito técnico, incluindo o contexto, a área afetada e as implicações. Seja o mais específico possível.
      value: |
        **Contexto:**
        Qual foi o cenário em que este débito técnico foi identificado? Isso está relacionado a uma funcionalidade específica ou um componente do sistema?

        **Problema:**
        Descreva o problema específico. Como ele impacta o código ou a funcionalidade? Há algum erro recorrente ou comportamento inesperado associado?

        **Impacto:**
        Como esse débito técnico afeta a operação ou o desenvolvimento contínuo? O impacto é imediato ou a longo prazo? Há degradação de performance, risco de falhas, ou impacto na manutenibilidade?

        **Área afetada:**
        Identifique as partes do código ou módulos que são impactados. Existem dependências críticas ou funcionalidades correlacionadas?

  - type: markdown
    attributes:
      value: |
        **---**

  - type: textarea
    id: passos_para_reproduzir
    attributes:
      label: Passos para Reproduzir
      description: Se possível, forneça instruções passo a passo para reproduzir o problema. Isso pode incluir scripts, comandos ou sequências de eventos no sistema.
      value: |
        **Passos para Reproduzir:**
        1. Descreva o primeiro passo claramente.
        2. Continue com os passos subsequentes.
        3. Adicione detalhes como comandos, dados específicos ou configurações utilizadas.

        **Comportamento Esperado:**
        O que deveria acontecer em um cenário ideal?

        **Comportamento Observado:**
        O que aconteceu em vez disso? Inclua logs ou mensagens de erro se relevante.

  - type: markdown
    attributes:
      value: |
        **---**

  - type: textarea
    id: solucoes_propostas
    attributes:
      label: Soluções Propostas ou Considerações
      description: Se possível, sugira uma solução ou explique o que poderia ser feito para mitigar ou resolver o débito técnico. Considere abordagens alternativas e seus possíveis impactos.
      value: |
        **Sugestão de Solução:**
        Se você tem uma ideia de como resolver esse problema, descreva a abordagem. Isso inclui mudanças no código, refatoração, atualizações de dependências, etc.

        **Considerações:**
        Existem riscos, impactos em outras áreas do sistema ou fatores que devem ser levados em conta na implementação da solução?

  - type: markdown
    attributes:
      value: |
        **---**

  - type: textarea
    id: notas_adicionais
    attributes:
      label: Notas Adicionais
      description: Adicione qualquer informação adicional que possa ser relevante para entender ou resolver o débito técnico. Exemplos incluem links para commits, pull requests, ou discussões prévias.
      value: |
        **Links úteis ou referências:** Inclua links para commits, pull requests, issues relacionadas, ou documentação que ajude a entender o problema em contexto.
