name: Débito Técnico
description: File a bug report.
title: "[Débito Técnico]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Relatório de Débito Técnico

        Obrigado por relatar um débito técnico! Este modelo ajudará a coletar informações detalhadas sobre o problema. Por favor, preencha todas as seções relevantes para que possamos entender completamente o que precisa ser melhorado.
  - type: dropdown
    id: tipo_debito_tecnico
    attributes:
      label: Tipo de Débito Técnico
      description: Selecione o tipo de débito técnico associado ao problema.
      options:
        - Código Duplicado
        - Falta de Testes Automatizados
        - Arquitetura Pobre
        - Dependências Desatualizadas
        - Documentação Incompleta
        - Performance Degradada
        - Complexidade Ciclomática Alta
        - Outros
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true