body:
  - type: markdown
    attributes:
      value: |
        ## Relatório de Débito Técnico

        Obrigado por relatar um débito técnico! Este modelo ajudará a coletar informações detalhadas sobre o problema. Por favor, preencha todas as seções relevantes para que possamos entender completamente o que precisa ser melhorado.

  - type: dropdown
    id: tipo_debito_tecnico
    attributes:
      label: Tipo de Débito Técnico
      description: Selecione o tipo de débito técnico associado ao problema.
      options:
        - value: codigo_duplicado
          label: Código Duplicado
        - value: falta_de_testes
          label: Falta de Testes Automatizados
        - value: arquitetura_pobre
          label: Arquitetura Pobre
        - value: dependencias_desatualizadas
          label: Dependências Desatualizadas
        - value: documentacao_incompleta
          label: Documentação Incompleta
        - value: performance_degradada
          label: Performance Degradada
        - value: complexidade_ciclica
          label: Complexidade Ciclomática Alta
        - value: outros
          label: Outros
    validations:
      required: true

  - type: textarea
    id: descricao_problema
    attributes:
      label: Descrição do Débito Técnico
      description: Descreva detalhadamente o débito técnico, incluindo o contexto, a área afetada e as implicações.
      placeholder: |
        **Contexto:**
        Qual é o contexto em que esse débito técnico foi identificado? Em que parte do sistema ele ocorre?

        **Problema:**
        Qual é o problema específico que você encontrou? Como ele afeta o sistema?

        **Impacto:**
        Quais são as consequências desse débito técnico? Ele afeta a performance, manutenibilidade ou outros aspectos do sistema?

        **Área afetada:**
        Quais partes do código, módulos ou componentes são afetados por esse débito técnico?
    validations:
      required: true

  - type: textarea
    id: passos_para_reproduzir
    attributes:
      label: Passos para Reproduzir
      description: Se aplicável, forneça passos para reproduzir o problema ou para observar o débito técnico em ação.
      placeholder: |
        **Passos para Reproduzir:**
        1. 
        2. 
        3. 

        **Comportamento Esperado:**
        O que você esperava que acontecesse?

        **Comportamento Observado:**
        O que aconteceu em vez do comportamento esperado?

  - type: textarea
    id: solucoes_propostas
    attributes:
      label: Soluções Propostas ou Considerações
      description: Se possível, sugira uma solução ou explique o que pode ser feito para resolver ou mitigar o débito técnico.
      placeholder: |
        **Sugestão de Solução:**
        Qual seria uma solução ideal para esse problema? Você tem alguma ideia de como ele poderia ser resolvido?

        **Considerações:**
        Existem riscos ou outros fatores que precisam ser considerados ao resolver esse débito técnico?

  - type: checkboxes
    id: impacto
    attributes:
      label: Impacto
      description: Selecione os impactos principais que esse débito técnico causa no sistema.
      options:
        - label: Performance
          value: performance
        - label: Manutenibilidade
          value: manutenibilidade
        - label: Segurança
          value: seguranca
        - label: Testabilidade
          value: testabilidade
        - label: Escalabilidade
          value: escalabilidade
        - label: Outros
          value: outros

  - type: input
    id: versão
    attributes:
      label: Versão Afetada
      description: Informe a versão do sistema que está sendo afetada por este débito técnico.
      placeholder: 'Ex: v1.2.3'

  - type: input
    id: ambiente
    attributes:
      label: Ambiente
      description: Informe o ambiente onde o débito técnico foi identificado (desenvolvimento, staging, produção).
      placeholder: 'Ex: Produção, Staging, Desenvolvimento'

  - type: textarea
    id: notas_adicionais
    attributes:
      label: Notas Adicionais
      description: Adicione qualquer informação adicional que possa ser relevante para entender ou resolver o débito técnico.
      placeholder: 'Outras informações ou detalhes que possam ser úteis.'