name: Teste
description: 'Teste'
title: '[Teste]'
labels: [teste,bug,valores]

body:
  - type: markdown
    attributes:
      value: |
        Teste Issue

  - type: textarea
    id: teste
    attributes:
      label: teste
    validations:
      required: false